### ISSUE TITLE
Error command encryptModel on PHP 7.3.11

### ISSUE THREAD

**Issue by ggarcia92** [magros/laravel-model-encryption#3]
When running `php artisan encryptable:encryptModel 'App\User'` it was raised the error: ` Call to undefined function Magros\Encryptable\str_contains()`

Environment:
- Ubuntu 19.09
- PHP 7.3.11
- Laravel 7

Regards

**Comment by ggarcia92** [comment]
My Solution was change the line `!str_contains($raw, $record->encrypter()->getPrefix())` for `!Illuminate\Support\Str::contains($raw, $record->encrypter()->getPrefix())`, on this way it was removed Php version dependency in that code section.

Regards

**Comment by magros** [comment]
Thanks for the pull request, it was an error with a deprecated helper from laravel.
