### ISSUE TITLE
 Illuminate\Database\Eloquent\Model and Magros\Encryptable\Encryptable define the same property ($encrypter) in the composition of

### ISSUE THREAD

**Issue by diazsasak** [magros/laravel-model-encryption#5]
Hello,

i think the package is conflict with the current laravel. i got this error when executing:

 php artisan encryptable:encryptModel 'App\Models\MyModel'

Illuminate\Database\Eloquent\Model and Magros\Encryptable\Encryptable define the same property ($encrypter) in the composition of App\Models\MyModel. However, the definition differs and is considered incompatible. Class was composed

**Comment by ggarcia92** [comment]
Fixed on #6 .

**Comment by magros** [comment]
Thanks @ggarcia92

**Comment by diazsasak** [comment]
Thank you @magros and @ggarcia92 🙂
